name: CI - Build and Push Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout your repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Log in to Docker Hub using your secrets
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build the Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/python-ci-demo:latest .

      # (Optional) Run tests inside the container
      - name: Run tests
        run: docker run --rm ${{ secrets.DOCKER_USERNAME }}/python-ci-demo:latest pytest -v || true

      # Push the image to Docker Hub
      - name: Push image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/python-ci-demo:latest

        #build